import Shirt from '../../src/assets/img/shirt.jpg';
import PostImg from '../../src/assets/img/postimg.jpg';

const mockProducts = [
  {
    id: 1,
    user: 'HIKO',
    name: 'Áo sơ mi trắng',
    category: 'Quần áo',
    isNew: true,
    given: false,
    img: [Shirt],
    images: [Shirt, PostImg],
    details: ['Còn mới 90%', 'Sạch sẽ'],
    description: ['Mặc vài lần, còn rất mới.'],
    tags: ['áo sơ mi', 'nam'],
    freeShip: true,
    hasBox: true,
  },
  {
    id: 2,
    user: 'HIKO',
    name: 'Áo sơ mi trắng',
    category: 'Quần áo',
    isNew: true,
    given: false,
    img: [Shirt],
    images: [Shirt, PostImg],
    details: ['Còn mới 90%', 'Sạch sẽ'],
    description: ['Mặc vài lần, còn rất mới.'],
    tags: ['áo sơ mi', 'nam'],
    freeShip: true,
    hasBox: true,
  },
  {
    id: 3,
    user: 'HIKO',
    name: 'Áo sơ mi trắng',
    category: 'Quần áo',
    isNew: true,
    given: false,
    img: [Shirt],
    images: [Shirt, PostImg],
    details: ['Còn mới 90%', 'Sạch sẽ'],
    description: ['Mặc vài lần, còn rất mới.'],
    tags: ['áo sơ mi', 'nam'],
    freeShip: true,
    hasBox: true,
  },
  {
    id: 4,
    user: 'HIKO',
    name: 'Áo sơ mi trắng',
    category: 'Quần áo',
    isNew: true,
    given: false,
    img: [Shirt],
    images: [Shirt, PostImg],
    details: ['Còn mới 90%', 'Sạch sẽ'],
    description: ['Mặc vài lần, còn rất mới.'],
    tags: ['áo sơ mi', 'nam'],
    freeShip: true,
    hasBox: true,
  },
  {
    id: 5,
    user: 'HIKO',
    name: 'Áo sơ mi trắng',
    category: 'Quần áo',
    isNew: true,
    given: false,
    img: [Shirt],
    images: [Shirt, PostImg],
    details: ['Còn mới 90%', 'Sạch sẽ'],
    description: ['Mặc vài lần, còn rất mới.'],
    tags: ['áo sơ mi', 'nam'],
    freeShip: true,
    hasBox: true,
  },
  {
    id: 6,
    user: 'HIKO',
    name: 'Áo sơ mi trắng',
    category: 'Quần áo',
    isNew: true,
    given: false,
    img: [Shirt],
    images: [Shirt, PostImg],
    details: ['Còn mới 90%', 'Sạch sẽ'],
    description: ['Mặc vài lần, còn rất mới.'],
    tags: ['áo sơ mi', 'nam'],
    freeShip: true,
    hasBox: true,
  },
  {
    id: 7,
    user: 'HIKO',
    name: 'Áo sơ mi trắng',
    category: 'Quần áo',
    isNew: true,
    given: false,
    img: [Shirt],
    images: [Shirt, PostImg],
    details: ['Còn mới 90%', 'Sạch sẽ'],
    description: ['Mặc vài lần, còn rất mới.'],
    tags: ['áo sơ mi', 'nam'],
    freeShip: true,
    hasBox: true,
  },
  {
    id: 8,
    user: 'HIKO',
    name: 'Balo học sinh',
    category: 'Đồ dùng học tập',
    isNew: false,
    given: true,
    img: [PostImg],
    images: [PostImg],
    details: ['Đã qua sử dụng'],
    description: ['Cho học sinh lớp 1, vẫn còn tốt.'],
    tags: ['balo', 'trẻ em'],
    freeShip: true,
    hasBox: true,
  },
  {
    id: 9,
    user: 'Thanh Trúc',
    name: 'Giày nữ công sở',
    category: 'Giày dép',
    isNew: true,
    given: false,
    img: [Shirt],
    images: [Shirt],
    details: ['Size 37', 'Mới'],
    description: ['Giày đẹp, chưa dùng.'],
    tags: ['giày', 'nữ'],
    freeShip: true,
    hasBox: true,
  },
  {
    id: 10,
    user: 'Thanh Trúc',
    name: 'Túi xách tay',
    category: 'Phụ kiện',
    isNew: false,
    given: true,
    img: [PostImg],
    images: [PostImg],
    details: ['Hàng đã dùng'],
    description: ['Túi xách đơn giản, còn dùng tốt.'],
    tags: ['túi xách', 'phụ kiện'],
    freeShip: true,
    hasBox: true,
  },
  {
    id: 11,
    user: 'Thanh Trúc',
    name: 'Túi xách tay',
    category: 'Phụ kiện',
    isNew: false,
    given: true,
    img: [PostImg],
    images: [PostImg],
    details: ['Hàng đã dùng'],
    description: ['Túi xách đơn giản, còn dùng tốt.'],
    tags: ['túi xách', 'phụ kiện'],
    freeShip: true,
    hasBox: true,
  },
  {
    id: 12,
    user: 'Thanh Trúc',
    name: 'Túi xách tay',
    category: 'Phụ kiện',
    isNew: false,
    given: true,
    img: [PostImg],
    images: [PostImg],
    details: ['Hàng đã dùng'],
    description: ['Túi xách đơn giản, còn dùng tốt.'],
    tags: ['túi xách', 'phụ kiện'],
    freeShip: true,
    hasBox: true,
  }
];

export const productService = {
  getAllProducts: () => mockProducts,
  getNewProducts: () => mockProducts.filter((p) => p.isNew),
  getPopularProducts: () => mockProducts.slice(0,8),
  getProductsByUser: (username, isGiven = false) =>
    mockProducts.filter((p) => p.user === username && p.given === isGiven),
  getProductById: (id) => mockProducts.find((p) => p.id === Number(id)),
};
