import Shirt from '../../src/assets/img/shirt.jpg';
import PostImg from '../../src/assets/img/postimg.jpg';

const mockProducts = [
  {id: 2,user: 'Thành Nhân',  category: 'Quần áo', name: 'Áo sơ mi nam', img:[ Shirt],images: [Shirt, PostImg, Shirt], isNew: true, details: ['Sạch sẽ, mới giặt', '90%', 'Thủ Đức, TP Hồ Chí Minh'], description: ['Áo sơ mi nam Việt Tiến là sự lựa chọn hàng đầu của giới công sở văn phòng bởi chất lượng vải tốt, thoáng mát cùng với những đường may tỉ mỉ, kiểu dáng lịch thiệp và hiện đại.','Sản phẩm áo sơ mi trắng Việt Tiến đã trở thành thương hiệu cho dòng sản phẩm công sở của Việt Tiến. Dù là mặc riêng hay phối cùng với vest đều toát lên vẻ lịch sự trang trọng cần có nhưng không kém phần thoải mái nhẹ nhàng cho người mặc.','Sau khi đặt hàng thành công sản phẩm áo sơ mi Trắng Việt Tiến, quý khách sẽ nhận được email xác nhận. Đồng thời, bộ phận chăm sóc khách hàng sẽ gọi điện liên hệ với quý khách để tư vấn chi tiết về sản phẩm, size áo và chế độ giao – trả hàng.',],tags: ['Áo sơ mi', 'Sơ mi nam', 'Áo nam', 'Áo công sở', 'Áo xanh', 'Lịch lãm'],freeShip: true, hasBox: true, },
  {id: 3,user: 'Thành Nhân', category: 'Quần áo', name: 'Áo sơ mi nam', img: [ Shirt],images: [Shirt, PostImg, Shirt], isNew: true, details: ['Sạch sẽ, mới giặt', '90%', 'Thủ Đức, TP Hồ Chí Minh'],description: ['Áo sơ mi nam Việt Tiến là sự lựa chọn hàng đầu của giới công sở văn phòng bởi chất lượng vải tốt, thoáng mát cùng với những đường may tỉ mỉ, kiểu dáng lịch thiệp và hiện đại.','Sản phẩm áo sơ mi trắng Việt Tiến đã trở thành thương hiệu cho dòng sản phẩm công sở của Việt Tiến. Dù là mặc riêng hay phối cùng với vest đều toát lên vẻ lịch sự trang trọng cần có nhưng không kém phần thoải mái nhẹ nhàng cho người mặc.','Sau khi đặt hàng thành công sản phẩm áo sơ mi Trắng Việt Tiến, quý khách sẽ nhận được email xác nhận. Đồng thời, bộ phận chăm sóc khách hàng sẽ gọi điện liên hệ với quý khách để tư vấn chi tiết về sản phẩm, size áo và chế độ giao – trả hàng.',],tags: ['Áo sơ mi', 'Sơ mi nam', 'Áo nam', 'Áo công sở', 'Áo xanh', 'Lịch lãm'], freeShip: true, hasBox: true, },
  {id: 4,user: 'Thành Nhân', category: 'Quần áo', name: 'Áo sơ mi nam', img: [ Shirt],images: [Shirt, PostImg, Shirt], isNew: true, details: ['Sạch sẽ, mới giặt', '90%', 'Thủ Đức, TP Hồ Chí Minh'], description: ['Áo sơ mi nam Việt Tiến là sự lựa chọn hàng đầu của giới công sở văn phòng bởi chất lượng vải tốt, thoáng mát cùng với những đường may tỉ mỉ, kiểu dáng lịch thiệp và hiện đại.','Sản phẩm áo sơ mi trắng Việt Tiến đã trở thành thương hiệu cho dòng sản phẩm công sở của Việt Tiến. Dù là mặc riêng hay phối cùng với vest đều toát lên vẻ lịch sự trang trọng cần có nhưng không kém phần thoải mái nhẹ nhàng cho người mặc.','Sau khi đặt hàng thành công sản phẩm áo sơ mi Trắng Việt Tiến, quý khách sẽ nhận được email xác nhận. Đồng thời, bộ phận chăm sóc khách hàng sẽ gọi điện liên hệ với quý khách để tư vấn chi tiết về sản phẩm, size áo và chế độ giao – trả hàng.',],tags: ['Áo sơ mi', 'Sơ mi nam', 'Áo nam', 'Áo công sở', 'Áo xanh', 'Lịch lãm'],freeShip: true, hasBox: true, },
  {id: 5, user: 'Thành Nhân', category: 'Quần áo', name: 'Áo sơ mi nam', img:[ Shirt], images: [Shirt, PostImg, Shirt],isNew: true, details: ['Sạch sẽ, mới giặt', '90%', 'Thủ Đức, TP Hồ Chí Minh'],description: ['Áo sơ mi nam Việt Tiến là sự lựa chọn hàng đầu của giới công sở văn phòng bởi chất lượng vải tốt, thoáng mát cùng với những đường may tỉ mỉ, kiểu dáng lịch thiệp và hiện đại.','Sản phẩm áo sơ mi trắng Việt Tiến đã trở thành thương hiệu cho dòng sản phẩm công sở của Việt Tiến. Dù là mặc riêng hay phối cùng với vest đều toát lên vẻ lịch sự trang trọng cần có nhưng không kém phần thoải mái nhẹ nhàng cho người mặc.','Sau khi đặt hàng thành công sản phẩm áo sơ mi Trắng Việt Tiến, quý khách sẽ nhận được email xác nhận. Đồng thời, bộ phận chăm sóc khách hàng sẽ gọi điện liên hệ với quý khách để tư vấn chi tiết về sản phẩm, size áo và chế độ giao – trả hàng.',],tags: ['Áo sơ mi', 'Sơ mi nam', 'Áo nam', 'Áo công sở', 'Áo xanh', 'Lịch lãm'], freeShip: true, hasBox: true, },
  {id: 6, user: 'Thành Nhân', category: 'Quần áo', name: 'Áo sơ mi nam', img: [ Shirt],images: [Shirt, PostImg, Shirt], isNew: true, details: ['Sạch sẽ, mới giặt', '90%', 'Thủ Đức, TP Hồ Chí Minh'],description: ['Áo sơ mi nam Việt Tiến là sự lựa chọn hàng đầu của giới công sở văn phòng bởi chất lượng vải tốt, thoáng mát cùng với những đường may tỉ mỉ, kiểu dáng lịch thiệp và hiện đại.','Sản phẩm áo sơ mi trắng Việt Tiến đã trở thành thương hiệu cho dòng sản phẩm công sở của Việt Tiến. Dù là mặc riêng hay phối cùng với vest đều toát lên vẻ lịch sự trang trọng cần có nhưng không kém phần thoải mái nhẹ nhàng cho người mặc.','Sau khi đặt hàng thành công sản phẩm áo sơ mi Trắng Việt Tiến, quý khách sẽ nhận được email xác nhận. Đồng thời, bộ phận chăm sóc khách hàng sẽ gọi điện liên hệ với quý khách để tư vấn chi tiết về sản phẩm, size áo và chế độ giao – trả hàng.',],tags: ['Áo sơ mi', 'Sơ mi nam', 'Áo nam', 'Áo công sở', 'Áo xanh', 'Lịch lãm'], freeShip: true, hasBox: true, },
  {id: 7, user: 'Thành Nhân', category: 'Quần áo', name: 'Áo sơ mi nam', img: [ Shirt],images: [Shirt, PostImg, Shirt], isNew: true, details: ['Sạch sẽ, mới giặt', '90%', 'Thủ Đức, TP Hồ Chí Minh'],description: ['Áo sơ mi nam Việt Tiến là sự lựa chọn hàng đầu của giới công sở văn phòng bởi chất lượng vải tốt, thoáng mát cùng với những đường may tỉ mỉ, kiểu dáng lịch thiệp và hiện đại.','Sản phẩm áo sơ mi trắng Việt Tiến đã trở thành thương hiệu cho dòng sản phẩm công sở của Việt Tiến. Dù là mặc riêng hay phối cùng với vest đều toát lên vẻ lịch sự trang trọng cần có nhưng không kém phần thoải mái nhẹ nhàng cho người mặc.','Sau khi đặt hàng thành công sản phẩm áo sơ mi Trắng Việt Tiến, quý khách sẽ nhận được email xác nhận. Đồng thời, bộ phận chăm sóc khách hàng sẽ gọi điện liên hệ với quý khách để tư vấn chi tiết về sản phẩm, size áo và chế độ giao – trả hàng.',],tags: ['Áo sơ mi', 'Sơ mi nam', 'Áo nam', 'Áo công sở', 'Áo xanh', 'Lịch lãm'], freeShip: true, hasBox: true, },
  {id: 8,user: 'Thành Nhân',  category: 'Quần áo', name: 'Áo sơ mi nam', img: [ Shirt], images: [Shirt, PostImg, Shirt],isNew: true, details: ['Sạch sẽ, mới giặt', '90%', 'Thủ Đức, TP Hồ Chí Minh'], description: ['Áo sơ mi nam Việt Tiến là sự lựa chọn hàng đầu của giới công sở văn phòng bởi chất lượng vải tốt, thoáng mát cùng với những đường may tỉ mỉ, kiểu dáng lịch thiệp và hiện đại.','Sản phẩm áo sơ mi trắng Việt Tiến đã trở thành thương hiệu cho dòng sản phẩm công sở của Việt Tiến. Dù là mặc riêng hay phối cùng với vest đều toát lên vẻ lịch sự trang trọng cần có nhưng không kém phần thoải mái nhẹ nhàng cho người mặc.','Sau khi đặt hàng thành công sản phẩm áo sơ mi Trắng Việt Tiến, quý khách sẽ nhận được email xác nhận. Đồng thời, bộ phận chăm sóc khách hàng sẽ gọi điện liên hệ với quý khách để tư vấn chi tiết về sản phẩm, size áo và chế độ giao – trả hàng.',],tags: ['Áo sơ mi', 'Sơ mi nam', 'Áo nam', 'Áo công sở', 'Áo xanh', 'Lịch lãm'],freeShip: true, hasBox: true, },
  {id: 9, user: 'Thành Nhân', category: 'Quần áo', name: 'Áo sơ mi nam', img:[ Shirt], images: [Shirt, PostImg, Shirt],isNew: true, details: ['Sạch sẽ, mới giặt', '90%', 'Thủ Đức, TP Hồ Chí Minh'], description: ['Áo sơ mi nam Việt Tiến là sự lựa chọn hàng đầu của giới công sở văn phòng bởi chất lượng vải tốt, thoáng mát cùng với những đường may tỉ mỉ, kiểu dáng lịch thiệp và hiện đại.','Sản phẩm áo sơ mi trắng Việt Tiến đã trở thành thương hiệu cho dòng sản phẩm công sở của Việt Tiến. Dù là mặc riêng hay phối cùng với vest đều toát lên vẻ lịch sự trang trọng cần có nhưng không kém phần thoải mái nhẹ nhàng cho người mặc.','Sau khi đặt hàng thành công sản phẩm áo sơ mi Trắng Việt Tiến, quý khách sẽ nhận được email xác nhận. Đồng thời, bộ phận chăm sóc khách hàng sẽ gọi điện liên hệ với quý khách để tư vấn chi tiết về sản phẩm, size áo và chế độ giao – trả hàng.',],tags: ['Áo sơ mi', 'Sơ mi nam', 'Áo nam', 'Áo công sở', 'Áo xanh', 'Lịch lãm'],freeShip: true, hasBox: true, },
  {id: 10, user: 'Thành Nhân', category: 'Quần áo', name: 'Áo sơ mi nam', img: [ Shirt],images: [Shirt, PostImg, Shirt], isNew: true, details: ['Sạch sẽ, mới giặt', '90%', 'Thủ Đức, TP Hồ Chí Minh'],description: ['Áo sơ mi nam Việt Tiến là sự lựa chọn hàng đầu của giới công sở văn phòng bởi chất lượng vải tốt, thoáng mát cùng với những đường may tỉ mỉ, kiểu dáng lịch thiệp và hiện đại.','Sản phẩm áo sơ mi trắng Việt Tiến đã trở thành thương hiệu cho dòng sản phẩm công sở của Việt Tiến. Dù là mặc riêng hay phối cùng với vest đều toát lên vẻ lịch sự trang trọng cần có nhưng không kém phần thoải mái nhẹ nhàng cho người mặc.','Sau khi đặt hàng thành công sản phẩm áo sơ mi Trắng Việt Tiến, quý khách sẽ nhận được email xác nhận. Đồng thời, bộ phận chăm sóc khách hàng sẽ gọi điện liên hệ với quý khách để tư vấn chi tiết về sản phẩm, size áo và chế độ giao – trả hàng.',],tags: ['Áo sơ mi', 'Sơ mi nam', 'Áo nam', 'Áo công sở', 'Áo xanh', 'Lịch lãm'], freeShip: true, hasBox: true, },
  {id: 11, user: 'Thành Nhân', category: 'Quần áo', name: 'Áo sơ mi nam', img: [ Shirt],images: [Shirt, PostImg, Shirt],isNew: true, details: ['Sạch sẽ, mới giặt', '90%', 'Thủ Đức, TP Hồ Chí Minh'], description: ['Áo sơ mi nam Việt Tiến là sự lựa chọn hàng đầu của giới công sở văn phòng bởi chất lượng vải tốt, thoáng mát cùng với những đường may tỉ mỉ, kiểu dáng lịch thiệp và hiện đại.','Sản phẩm áo sơ mi trắng Việt Tiến đã trở thành thương hiệu cho dòng sản phẩm công sở của Việt Tiến. Dù là mặc riêng hay phối cùng với vest đều toát lên vẻ lịch sự trang trọng cần có nhưng không kém phần thoải mái nhẹ nhàng cho người mặc.','Sau khi đặt hàng thành công sản phẩm áo sơ mi Trắng Việt Tiến, quý khách sẽ nhận được email xác nhận. Đồng thời, bộ phận chăm sóc khách hàng sẽ gọi điện liên hệ với quý khách để tư vấn chi tiết về sản phẩm, size áo và chế độ giao – trả hàng.',],tags: ['Áo sơ mi', 'Sơ mi nam', 'Áo nam', 'Áo công sở', 'Áo xanh', 'Lịch lãm'],freeShip: true, hasBox: true, },
  {id: 12,user: 'Thành Nhân',  category: 'Quần áo', name: 'Áo sơ mi nam', img: [ Shirt],images: [Shirt, PostImg, Shirt],isNew: true, details: ['Sạch sẽ, mới giặt', '90%', 'Thủ Đức, TP Hồ Chí Minh'],description: ['Áo sơ mi nam Việt Tiến là sự lựa chọn hàng đầu của giới công sở văn phòng bởi chất lượng vải tốt, thoáng mát cùng với những đường may tỉ mỉ, kiểu dáng lịch thiệp và hiện đại.','Sản phẩm áo sơ mi trắng Việt Tiến đã trở thành thương hiệu cho dòng sản phẩm công sở của Việt Tiến. Dù là mặc riêng hay phối cùng với vest đều toát lên vẻ lịch sự trang trọng cần có nhưng không kém phần thoải mái nhẹ nhàng cho người mặc.','Sau khi đặt hàng thành công sản phẩm áo sơ mi Trắng Việt Tiến, quý khách sẽ nhận được email xác nhận. Đồng thời, bộ phận chăm sóc khách hàng sẽ gọi điện liên hệ với quý khách để tư vấn chi tiết về sản phẩm, size áo và chế độ giao – trả hàng.',],tags: ['Áo sơ mi', 'Sơ mi nam', 'Áo nam', 'Áo công sở', 'Áo xanh', 'Lịch lãm'], freeShip: true, hasBox: true, },
];

export const productService = {
  getAllProducts: () => mockProducts,

  getNewProducts: () => mockProducts.filter((p) => p.isNew),

  getPopularProducts: () => mockProducts.slice(),

  getProductsByUser: (name) => mockProducts.filter(p => p.user === name),

  getProductById: (id) => mockProducts.find((p) => p.id === Number(id)),

};
